# Generated by Django 5.1 on 2024-12-03 17:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investimentos', '0002_transacao_valor_total_saldo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ativo',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
